### ISSUE TITLE
eloquent-ldap fail 

### ISSUE THREAD

**Issue by dsnoeck** [leskhq/Laravel-Enterprise-Starter-Kit#82]
Since I ran ```composer update``` I have this issue:

```
PHP Fatal error:  Uncaught Error: Class 'Setting' not found in /path/to/my/app/vendor/sroutier/eloquent-ldap/src/Providers/EloquentLDAPUserProvider.php:71
Stack trace:
#0 /path/to/my/app/vendor/sroutier/eloquent-ldap/src/Providers/EloquentLDAPServiceProvider.php(39): Sroutier\EloquentLDAP\Providers\EloquentLDAPUserProvider->__construct(Object(Illuminate\Foundation\Application))
#1 /path/to/my/app/vendor/laravel/framework/src/Illuminate/Support/Manager.php(101): Sroutier\EloquentLDAP\Providers\EloquentLDAPServiceProvider->Sroutier\EloquentLDAP\Providers\{closure}(Object(Illuminate\Foundation\Application))
#2 /path/to/my/app/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(46): Illuminate\Support\Manager->callCustomCreator('eloquent-ldap')
#3 /path/to/my/app/vendor/laravel/framework/src/Illuminate/Support/Manager.php(85): Illuminate\Auth\AuthManager- in /path/to/my/app/vendor/sroutier/eloquent-ldap/src/Providers/EloquentLDAPUserProvider.php on line 71
PHP Fatal error:  Uncaught Error: Class 'Setting' not found in /path/to/my/app/vendor/sroutier/eloquent-ldap/src/Providers/EloquentLDAPUserProvider.php:71
Stack trace:
#0 /path/to/my/app/vendor/sroutier/eloquent-ldap/src/Providers/EloquentLDAPServiceProvider.php(39): Sroutier\EloquentLDAP\Providers\EloquentLDAPUserProvider->__construct(Object(Illuminate\Foundation\Application))
#1 /path/to/my/app/vendor/laravel/framework/src/Illuminate/Support/Manager.php(101): Sroutier\EloquentLDAP\Providers\EloquentLDAPServiceProvider->Sroutier\EloquentLDAP\Providers\{closure}(Object(Illuminate\Foundation\Application))
#2 /path/to/my/app/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(46): Illuminate\Support\Manager->callCustomCreator('eloquent-ldap')
#3 /path/to/my/app/vendor/laravel/framework/src/Illuminate/Support/Manager.php(85): Illuminate\Auth\AuthManager- in /path/to/my/app/vendor/sroutier/eloquent-ldap/src/Providers/EloquentLDAPUserProvider.php on line 71
```

For info it update eloquent-ldap:
```
$ composer update
...
  - Removing sroutier/eloquent-ldap (dev-master 2dcbe90)
  - Installing sroutier/eloquent-ldap (dev-master eee260f) Downloading: 100%
...
```

**Comment by sroutier** [comment]
Hello Damien,

Did you make sure to get the latest code for the LESK? 
The latest version of ELOQUENT-LDAP requires the use of the matching version of LESK (or higher).

Let me know.
/S

**Comment by dsnoeck** [comment]
Thanks, I update LESK code to latest and if fix the issue.
