### ISSUE TITLE
error when run : php artisan ide-helper:models

### ISSUE THREAD

**Issue by sugengsuprayogi** [leskhq/Laravel-Enterprise-Starter-Kit#86]
`Do you want to overwrite the existing model files? Choose no to write to _ide_helper_models.php instead? (Yes/No):  (yes/no) [no]:
 > no

PHP Fatal error:  Cannot use Illuminate\Support\Arr as Arr because the name is already in use in G:\PROJECT\php\lms-bi\app\Libraries\Utils.php on line 9
PHP Fatal error:  Uncaught Error: Class 'App\Libraries\Utils' not found in G:\PROJECT\php\lms-bi\app\Models\Setting.php:128
Stack trace:
#0 G:\PROJECT\php\lms-bi\app\Managers\SettingManager.php(66): App\Models\Setting->get('lern.enable_rec...', NULL)
#1 G:\PROJECT\php\lms-bi\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(217): App\Managers\SettingManager->get('lern.enable_rec...')
#2 G:\PROJECT\php\lms-bi\app\Exceptions\Handler.php(41): Illuminate\Support\Facades\Facade::__callStatic('get', Array)
#3 G:\PROJECT\php\lms-bi\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(79): App\Exceptions\Handler->report(Object(Symfony\Component\Debug\Exceptio
n\FatalErrorException))
#4 G:\PROJECT\php\lms-bi\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Obj
ect(Symfony\Component\Debug\Exception\FatalErrorException))
#5 [internal function]: Illuminate\Foundation\Bootstrap\HandleException in G:\PROJECT\php\lms-bi\app\Models\Setting.php on line 128`

**Comment by sroutier** [comment]
Hello @sugengsuprayogi, apologies for the late reply.
Did you make any progress on this issue? 
I will make sure that it works for the next version.
